// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CPU = require("./CPU.bs.js");
var RomLoader = require("./RomLoader.bs.js");
var CamlinternalLazy = require("bs-platform/lib/js/camlinternalLazy.js");

var rom = RomLoader.toBuffer(CamlinternalLazy.force(RomLoader.load));

CPU.init(rom);

exports.rom = rom;
/* rom Not a pure module */
