// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

var load = {
  LAZY_DONE: false,
  VAL: (function () {
      console.log("Reading temporary from memory");
      return "60006100a222c2013201a21ed0147004304012046000710431201204121c8040201020408010";
    })
};

function toBuffer(hex) {
  return Caml_option.null_to_opt(hex.match(/.{1,2}/g));
}

exports.load = load;
exports.toBuffer = toBuffer;
/* No side effect */
